version: 3.8

services:
  web:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image:
      stredsearch-django-webserver
    command:
      /start
    volumes:
      - .:/app
    ports:
      - 8010:8000
    env_file:
      - ./.env/.dev-sample
    depends_on:
      - redis
      - db
  
  db:
    image:
      postgres:16-bookworm
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=compton-db
      - POSTGRES_USER=matt
      - POSTGRES_PASSWORD=Delta323!
  
  redis:
    image:
      redis:7-bookworm

  celery_worker:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image:
      stredsearch-celery-worker
    command:
      /start-celeryworker
    volumes:
      - .:/app
    env_file:
      - ./.env/.dev-sample
    depends_on:
      - redis
      - db

  celery_beat:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image:
      stredsearch-celery-beat
    command:
      /start-celerybeat
    volumes:
      - ./.env/.dev-sample
    depends_on:
      - redis
      - db

  flower:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image:
      stredsearch-celery-flower
    command: /start-flower
    volumes:
      - .:/app
    env_file:
      - ./.env/.dev-sample
    ports:
      - ./.env/.dev-sample
    depends_on:
      - redis
      - db

volumes:
  postgres_data: