# Dockerfile

# The first instruction is what image we want to base our container on
# We Use an official Python runtime as a parent image
FROM python:3.7

# Allows docker to cache installed dependencies between builds
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

# Mounts the application code to the image

WORKDIR /usr/src/

COPY ./ ./

RUN chmod +x server-entrypoint.sh
RUN chmod +x worker-entrypoint.sh

WORKDIR /usr/src/stredsearch

EXPOSE 8000





# runs the production server
# ENTRYPOINT ["python", "manage.py"]
# CMD [["makemigrations"], ["migrate"], ["runserver", "0.0.0.0:8000"]]