version: '3.8'

services:
    nginx:
        restart: always
        image: nginx:1.25.2-bookworm
        ports:
            - 80:80
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - static_volume:/app/stredsearch/django_static
    server:
        restart: unless-stopped
        build:
            context: .
            dockerfile: ./docker/stredsearch/Dockerfile
        entrypoint: /app/docker/stredsearch/server-entrypoint.sh
        volumes:
            - static_volume:/app/stredsearch/django_static
        expose:
            - 8000     
        environment:
            DEBUG: "True"
            CELERY_BROKER_URL: "redis://redis:6379/0"
            CELERY_RESULT_BACKEND: "redis://redis:6379/0"
            DJANGO_DB: postgresql
            POSTGRES_HOST: db
            POSTGRES_NAME: postgres
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_PORT: 5432
    worker:
        restart: unless-stopped
        build:
            context: .
            dockerfile: ./docker/stredsearch/Dockerfile
        entrypoint: /app/docker/stredsearch/worker-entrypoint.sh
        volumes:
            - .:/project
            # - static_volume:/app/stredsearch/django_static
        environment:
            DEBUG: "True"
            CELERY_BROKER_URL: "redis://redis:6379/0"
            CELERY_RESULT_BACKEND: "redis://redis:6379/0"
            DJANGO_DB: postgresql
            POSTGRES_HOST: db
            POSTGRES_NAME: postgres
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_PORT: 5432
        depends_on:
            - db
            - server
            - redis
    redis:
        restart: unless-stopped
        image: redis:7.2.2-bookworm 
        expose:
            - 6379
    db:
        image: postgres:16.0-bookworm
        restart: unless-stopped
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment:
            POSTGRES_DB: postgres
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        expose:
            - 5432
    
volumes:
    static_volume: {}
    postgres_data: {}