# Generated by Django 4.2.6 on 2023-10-23 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StackMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_prepend', models.CharField(max_length=200)),
                ('route_append', models.CharField(max_length=200)),
                ('filters', models.JSONField()),
                ('sort', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='StackRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_root', models.CharField(default='', max_length=200)),
                ('route', models.CharField(default='', max_length=200)),
                ('params', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='StackSearchTerms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_term', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='StackTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StackUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('display_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='StredSearchQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on_stredsearch', models.DateTimeField(auto_now_add=True)),
                ('updated_on_stredsearch', models.DateTimeField(auto_now=True)),
                ('link', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('times_returned_as_search_result', models.IntegerField(default=0)),
                ('search_term', models.ManyToManyField(blank=True, to='search.stacksearchterms')),
            ],
        ),
        migrations.CreateModel(
            name='RedditQuestion',
            fields=[
                ('stredsearchquestion_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='search.stredsearchquestion')),
                ('type', models.CharField(max_length=10)),
            ],
            bases=('search.stredsearchquestion',),
        ),
        migrations.CreateModel(
            name='StackQuestion',
            fields=[
                ('stredsearchquestion_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='search.stredsearchquestion')),
                ('is_answered', models.BooleanField()),
                ('view_count', models.IntegerField()),
                ('answer_count', models.IntegerField()),
                ('score', models.IntegerField()),
                ('last_activity_date', models.DateTimeField()),
                ('creation_date', models.DateTimeField()),
                ('last_edit_date', models.DateTimeField(blank=True)),
                ('question_id', models.IntegerField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='search.stackuser')),
                ('tags', models.ManyToManyField(to='search.stacktags')),
            ],
            bases=('search.stredsearchquestion',),
        ),
    ]
