# Generated by Django 4.2.6 on 2023-10-26 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stackuser',
            name='gibberish',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
