# Generated by Django 4.2.6 on 2023-10-23 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stredsearchquestion',
            name='times_returned_as_search_rsdfsdfsdesult',
            field=models.IntegerField(default=0),
        ),
    ]
