# Generated by Django 4.2.6 on 2023-11-01 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stacktags',
            name='number_of_cached_instances',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
