# Generated by Django 4.2.6 on 2023-10-23 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_stredsearchquestion_times_returned_as_search_rsdfsdfsdesult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stredsearchquestion',
            name='times_returned_as_search_rsdfsdfsdesult',
        ),
    ]
