# Generated by Django 4.2.6 on 2023-10-23 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_remove_stredsearchquestion_times_returned_as_search_rsdfsdfsdesult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stackquestion',
            name='tags',
            field=models.ManyToManyField(blank=True, to='search.stacktags'),
        ),
        migrations.AlterField(
            model_name='stredsearchquestion',
            name='search_term',
            field=models.ManyToManyField(null=True, to='search.stacksearchterms'),
        ),
    ]
