# Generated by Django 4.2.6 on 2023-11-01 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_alter_stacktags_number_of_instances_on_so'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stacksearchterms',
            name='search_term',
            field=models.CharField(max_length=500, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='stacktags',
            name='tag_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='stackuser',
            name='user_id',
            field=models.IntegerField(unique=True),
        ),
    ]
