# Generated by Django 4.2.6 on 2023-11-02 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_alter_stacksearchterms_search_term_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redditquestion',
            name='type',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
