# Generated by Django 4.2.6 on 2023-10-23 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_alter_stacksearchterms_search_term_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stackquestion',
            name='last_edit_date',
            field=models.DateTimeField(null=True),
        ),
    ]
