# Generated by Django 4.2.6 on 2023-11-02 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_alter_redditquestion_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StackSearchTerms',
            new_name='SearchTerms',
        ),
    ]
