# Generated by Django 4.2.6 on 2023-11-02 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0006_rename_stacksearchterms_searchterms'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedditSearchType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='redditquestion',
            name='type',
        ),
        migrations.AddField(
            model_name='redditquestion',
            name='type',
            field=models.ManyToManyField(blank=True, to='search.redditsearchtype'),
        ),
    ]
