# Generated by Django 4.2.6 on 2023-11-02 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0007_redditsearchtype_remove_redditquestion_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='redditsearchtype',
            old_name='type',
            new_name='search_type',
        ),
    ]
