# Generated by Django 4.2.6 on 2023-11-02 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0008_rename_type_redditsearchtype_search_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='redditquestion',
            old_name='type',
            new_name='search_type',
        ),
    ]
