# Generated by Django 4.2.6 on 2023-11-07 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0009_rename_type_redditquestion_search_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stackuser',
            name='display_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
