# Generated by Django 4.2.6 on 2023-11-23 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0010_alter_stackuser_display_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedditSubreddit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subreddit_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
