# Generated by Django 4.2.6 on 2023-11-23 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0011_redditsubreddit'),
    ]

    operations = [
        migrations.AddField(
            model_name='redditquestion',
            name='subreddit',
            field=models.ManyToManyField(blank=True, to='search.redditsubreddit'),
        ),
    ]
