# Generated by Django 4.2.6 on 2023-12-06 12:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('search', '0012_redditquestion_subreddit'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSearchResponses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reddit_responses', models.ManyToManyField(to='search.redditquestion')),
                ('search_term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='search.searchterms')),
                ('stack_responses', models.ManyToManyField(to='search.stackquestion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
