# Generated by Django 4.2.6 on 2023-12-06 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0013_usersearchresponses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersearchresponses',
            name='search_term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='search.searchterms'),
        ),
    ]
